// This file is autogenerated and will be overwritten by the configuration process

#include "local-downcast-plugins-comp.cpp"
#include "local-downcast-plugins-fbc.cpp"
#include "local-downcast-plugins-layout.cpp"
#include "local-downcast-plugins-qual.cpp"

