// This file is autogenerated and will be overwritten by the configuration process

#include "local-downcast-namespaces-comp.cpp"
#include "local-downcast-namespaces-fbc.cpp"
#include "local-downcast-namespaces-layout.cpp"
#include "local-downcast-namespaces-qual.cpp"

