// This file is autogenerated and will be overwritten by the configuration process

#include "local-downcast-extension-comp.cpp"
#include "local-downcast-extension-fbc.cpp"
#include "local-downcast-extension-layout.cpp"
#include "local-downcast-extension-qual.cpp"

