/* This file is autogenerated and will be overwritten by the configuration process */

#include <sbml/packages/comp-register.cxx>
#include <sbml/packages/fbc-register.cxx>
#include <sbml/packages/groups-register.cxx>
#include <sbml/packages/l3v2extendedmath-register.cxx>
#include <sbml/packages/layout-register.cxx>
#include <sbml/packages/multi-register.cxx>
#include <sbml/packages/qual-register.cxx>
#include <sbml/packages/render-register.cxx>

