/* This file is autogenerated and will be overwritten by the configuration process */

#include <sbml/packages/comp-register.cxx>
#include <sbml/packages/fbc-register.cxx>
#include <sbml/packages/layout-register.cxx>
#include <sbml/packages/qual-register.cxx>

