name: Build python-libsbml Wheels

on:
  workflow_dispatch:
  
jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: recursive  # Optional, use if you have submodules

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz
        name: sdist
  
  build_wheels:
    name: Wheel on ${{ matrix.os }} for ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        python_version: ['cp37-*', 'cp38-*', 'cp39-*', 'cp310-*', 'cp311-*', 'cp312-*']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: pypa/cibuildwheel@v2.16.2
      env:
          CIBW_BUILD: ${{ matrix.python_version }}
          CIBW_ARCHS_MACOS: x86_64 arm64

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl      
